subscription_id   = "1006154a-1e66-4d15-8a0b-60e356428bc1"
github_repo_owner = "mingfeiw"
github_repo_name  = "bookapi-minimal-infrastructure"
acr_name          = "acrbookapi"
rg_name           = "rg-bookapi-minimal"
aks_name          = "aks-bookapi-minimal"
admin_username    = "mingfeiadmin"