name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: acrbookapi

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: build and push image from source repo
        uses: actions/checkout@v3
        with:
          repository: mingfeiw/bookapi-minimal
          token: ${{ secrets.GITHUB_TOKEN }}
          path: src

      - name: Build docker image
        run: |
          cd src
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/bookapi-minimal:latest .

      - name: Push docker image to ACR
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/bookapi-minimal:latest

      - name: get aks credentials
        run: az aks get-credentials --resource-group rg-bookapi-minimal --name aks-bookapi-minimal

      - name: Deploy manifests
        run: kubectl apply -f k8s/